name: 'PR: Astro Check'

on:
  pull_request:
    branches:
      - main

jobs:
  astro-check:
    name: 'Run Astro check'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: src/package-lock.json
                
      - name: Install dependencies
        working-directory: ./src
        run: npm install

      - name: Run astro check
        working-directory: ./src
        run: npm run check
