name: 'PR: Bun Check'

on:
  pull_request:
    branches:
      - main

jobs:
  bun-check:
    name: 'Run bun check in ./src'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        # You may pin to the exact commit or the version.
        # uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76
        uses: oven-sh/setup-bun@v2
                
      - name: Install dependencies
        working-directory: ./src
        run: bun install

      - name: Run bun check
        working-directory: ./src
        run: bun check
