name: 'PR: Astro Check'

on:
  pull_request:
    branches:
      - main

jobs:
  astro-check:
    name: 'Run Astro check'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
                
      - name: Install dependencies
        working-directory: ./src
        run: bun install

      - name: Run astro check
        working-directory: ./src
        run: bun check
