name: 'PR: Bun Check'

on:
  pull_request:
    branches:
      - main

jobs:
  bun-check:
    name: 'Run bun check in ./src'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo 'export BUN_INSTALL="$HOME/.bun"' >> $GITHUB_ENV
          echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> $GITHUB_ENV

      - name: Install dependencies
        working-directory: ./src
        run: bun install

      - name: Run bun check
        working-directory: ./src
        run: bun check
